name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: source
      run: export CC=gcc-bin/arm-none-gnueabihf-gcc && export PATH=bin:$PATH
    - name: make
      run: make
